packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 1.9.4
  '@types/node': 22.14.1
  '@types/react': 19.1.1
  '@types/react-dom': 19.1.2
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
  vite: 6.2.6

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js-pure
  - esbuild
